version: 2.1

orbs:
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.3

# Install go version 1.19 to run our integration tests on the minimal version we support
setup_kurtosis: &setup_kurtosis
  - run: |
      echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
      sudo apt update
      sudo apt install kurtosis-cli
      kurtosis analytics disable
      kurtosis engine restart

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2004:202201-02

parameters:
  # To enable/disabled the check_latest_version workflow execution which will be triggered by this scheduled pipeline: https://app.circleci.com/settings/project/github/kurtosis-tech/eth-network-package/triggers
  should-enable-check-latest-version-workflow:
    type: boolean
    default: false
  # To enable/disabled the check_code workflow execution which will be triggered by the PR's checkers
  should-enable-build-workflow:
    type: boolean
    default: true

# NOTE: Because CircleCI jobs run on separate machines from each other, we duplicate steps (like checkout) between jobs. This is because doing the "correct" DRY
#  refactoring of, "one job for checkout, one job for build Docker image, etc." would require a) persisting files between jobs and b) persisting Docker images between
#  jobs. Both are annoying (saving/loading workspaces require re-downloading the workspace over the network, and there doesn't seem to be a good way to do Docker
#  images), so we run everything inside a single job.
# See also: https://discuss.circleci.com/t/can-docker-images-be-preserved-between-jobs-in-a-workflow-without-a-manual-load-save/23388/12
jobs:
  run_starlark:
    executor: ubuntu_vm
    steps:
      - checkout
      - <<: *setup_kurtosis
      - run: kurtosis run ${PWD}

  lint:
    executor: ubuntu_vm
    steps:
      - checkout
      - <<: *setup_kurtosis
      - run: kurtosis lint ${PWD}

  run_starlark_arm64:
    executor: ubuntu_vm
    resource_class: arm.medium
    steps:
      - checkout
      - <<: *setup_kurtosis
      - run: kurtosis run ${PWD}

  check_latest_version:
    executor: ubuntu_vm
    steps:
      - checkout
      - <<: *setup_kurtosis
      - run: kurtosis run ${PWD} --dry-run

workflows:
  check_latest_version:
    when: << pipeline.parameters.should-enable-check-latest-version-workflow >>
    jobs:
      - check_latest_version:
          context:
            - slack-secrets

  build:
    when: << pipeline.parameters.should-enable-build-workflow >>
    jobs:
      # -- PR check jobs ------------------------------------------
      - run_starlark:
          filters:
            branches:
              ignore:
                - main
      - run_starlark_arm64:
          filters:
            branches:
              ignore:
                - main                
      - lint:
          filters:
            branches:
              ignore:
                - main